services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    mem_limit: 10m
    cpus: "0.17"

  backend1:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/made_backend_test
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 200m
    cpus: "0.5"

  backend2:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/made_backend_test
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 200m
    cpus: "0.5"

  db:
    image: postgres:15-alpine
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/made_backend_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: made_backend_test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d made_backend_test"]
      interval: 5s
      timeout: 3s
      retries: 20
    mem_limit: 140m
    cpus: "0.33"
